apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aether-proxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: aether-proxy
    spec:
      containers:
        - name: aether-proxy
          image: nginx:1.13.5
          ports:
            - containerPort: 443
              protocol: TCP
              name: https
            - containerPort: 80
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: certs
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-config
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx-config
      volumes:
        - name: certs
          secret:
            secretName: nginx-cert
        - name: nginx-config
          configMap:
            name: nginx-config