apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aether-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: aether-app
    spec:
      containers:
        - name: aether
          image: gabiskandar/aether:0.2
          env:
            - name: NAAMIO_SOURCE
              value: aether
            - name: NAAMIO_TEMPLATES
              value: aether/stencils/
          ports:
            - containerPort: 8090
              protocol: TCP
              name: naamio