apiVersion: v1
kind: Service
metadata:
  name: aether-app
  labels:
    app: aether-app
spec:
  clusterIP: "10.0.0.180"
  selector:
    app: aether-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      name: http